### PR TITLE
Home Page

### PR DESCRIPTION
**Pull request by sedea23**
Home page Frontend done, except the charts

### CODE REVIEW

**Comment by frske** [comment]
Idk if it is intended behaviour but welcome page is not accessible aka is not in the route

**Review by frske — APPROVED** [review]
LGTM

**Review by Kacper-Grzyb — CHANGES_REQUESTED** [review]
Please improve the alignment between the boxes on the page 
obraz

**Comment by sedea23** [comment]
Changes met, waiting for review

**Review by Kacper-Grzyb — APPROVED** [review]
lgtm

**Pull request merged**
