### PR TITLE
Price Alert Features

### PR DESCRIPTION
**Pull request by Leonardo-Gianola**
- Added a price alert button on the set details page, which creates price alerts for the set number and a target price of the Lego set.

- Created a notification page with its own bell icon in the navbar, to check the notifications.

- Created PriceAlert Controller and Notification Controller, models and tables.

- Create a observer to check if the set_prices table changed and compare it with the alert target price.

### CODE REVIEW

**Review by Kacper-Grzyb — CHANGES_REQUESTED** [review]
Please update adding notifications to work with francesco's set-details page
Also please update your docker-compose.yml to:
```yml
services:
    laravel.application:
        build:
            context: './vendor/laravel/sail/runtimes/8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.3/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
networks:
    sail:
        driver: bridge
 ```
 As with the initial one I could not connect to the website.
 Otherwise lgtm, seems to be working

**Comment by Leonardo-Gianola** [comment]
Price alerts now work with Francesco's set details page

**Review by sedea23 — APPROVED** [review]
Tried it, everything seems to be working

**Comment by frske** [comment]
really good work

**Pull request merged**
